---
name: "clean_TE_inbox"
pack: "ductus_clean"
description: "Rule that triggers cleaning of inbox data for TE"
enabled: false

trigger:
  type: "core.st2.CronTimer"
  parameters:
    timezone: "UTC"
    day_of_week: 5 # or day_of_week: "sun"
    hour: 0
    minute: 0
    second: 0

action:
  ref: "ductus_clean.clean_wp3_TE_inbox"
