---
name: "clean_TC_inbox_outbox"
pack: "ductus_clean"
description: "Rule that triggers cleaning of inbox and outbox data for WP3 TC"
enabled: false

trigger:
  type: "core.st2.CronTimer"
  parameters:
    timezone: "UTC"
    day_of_week: 4 # or day_of_week: "sun"
    hour: 0
    minute: 0
    second: 0

action:
  ref: "ductus_clean.clean_wp3_TC_inbox_outbox"
